### ISSUE TITLE
Error: No such module 'Core'

### ISSUE THREAD

**Issue by NihanthCW** [ittybittyapps/ARVisualizer#2]
hello,

I followed the instructions but I keep getting the following error:

Swift Compile error  - > No such module 'Core' 
It points to **BasicAnchorNode.swift** in **ClientCore** 

You can reproduce the error by following the instructions and build and run for MobileClient.

I am using a macOS high Sierra v 10.13.6
Xcode version: 10.1
target Device: iPad 2017 running iOS 12.1

Thanks,

**Comment by orj** [comment]
Hi @NihanthCW 

Make sure you've loaded the `ARVisualiser.xcworkspace` in Xcode and have selected the correct scheme.

I can't reproduce your problem at my end.
